<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Exercises : Cleaning and Combining Data With pandas Part 1: 
# Cleaning Data

---

In [39]:
import pandas as pd

In [40]:
# 6.1 Identifying Missing Data
# We will use the orders table from Super Store for these tasks
orders = pd.read_csv('./data/orders.csv')

orders.head(3)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0
2,ES-2018-853948,28/07/2018 00:00,29/07/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,77095.0,1488.0

In [41]:
# A. Start with some exploratory analysis methods to inspect the data
orders.describe(include='all')

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id
count,990677,990677,990677,990677,990677,990677,990677.000000,990677.000000,990677.000000,990677.000000,191101.000000,990484.000000
unique,966545,1500,1502,4,795,10291,NaN,NaN,NaN,NaN,NaN,NaN
top,CA-2019-100111,30/11/2019 00:00,07/12/2019 00:00,Standard Class,BE-11335,OFF-AR-10003829,NaN,NaN,NaN,NaN,NaN,NaN
freq,14,2631,2573,401126,2291,613,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,245.755934,3.476170,0.247240,1.588697,55356.162197,6370.767934
std,NaN,NaN,NaN,NaN,NaN,NaN,481.529377,2.285935,0.137289,38.921319,32147.298661,10458.933204
min,NaN,NaN,NaN,NaN,NaN,NaN,0.440000,1.000000,0.000000,-6599.980000,1040.000000,38.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,30.640000,2.000000,0.130000,0.100000,23320.000000,2125.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,84.770000,3.000000,0.250000,0.200000,57103.000000,3688.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,250.400000,5.000000,0.350000,0.290000,90049.000000,5636.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.670000,8399.980000,99301.000000,98923.000000

In [42]:
# NO CODE HERE PLEASE

In [43]:
# B. Which column has the most missing data? Sort the columns by sum of null values
orders.isnull().sum().to_frame('nulls').sort_values('nulls', ascending=False)

              nulls
postal_code  799576
region_id       193
order_id          0
order_date        0
ship_mode         0
ship_date         0
customer_id       0
product_id        0
quantity          0
sales             0
profit            0
discount          0

In [44]:
# NO CODE HERE PLEASE

In [45]:
# C. Looks like postal_code is our biggest problem, along with region_id
# Use a combination of filtering, isnull, and sum to count how many rows are missing both columns
len(orders[(orders['postal_code'].isnull()) & (orders['region_id'].isnull())])

193

In [46]:
# NO CODE HERE PLEASE

In [47]:
# D. Let's drop the region_id nulls from the dataframe before proceeding
orders = orders.dropna(subset=['region_id'])
orders.isnull().sum().to_frame('nulls').sort_values('nulls', ascending=False)

              nulls
postal_code  799383
order_id          0
ship_date         0
order_date        0
ship_mode         0
customer_id       0
sales             0
product_id        0
quantity          0
discount          0
profit            0
region_id         0

In [48]:
# NO CODE HERE PLEASE

Our IT team confirmed that all missing postal code values should be 10001. Let's fill the null values using a built-in pandas function called `.fillna()`. This function will fill all the null values with a specified replacement, and it accepts the `inplace = True` statement to make our changes stick.

In [50]:
# E. It's the dream scenario! The IT team confirms all missing postal_code values should be 10001.0
orders['postal_code']=orders['postal_code'].fillna(10001)
orders.isnull().sum()

order_id       0
order_date     0
ship_date      0
ship_mode      0
customer_id    0
product_id     0
sales          0
quantity       0
discount       0
profit         0
postal_code    0
region_id      0
dtype: int64

In [15]:
# NO CODE HERE PLEASE

order_id       0
order_date     0
ship_date      0
ship_mode      0
customer_id    0
product_id     0
sales          0
quantity       0
discount       0
profit         0
postal_code    0
region_id      0
dtype: int64

In [51]:
# 6.2 Cleaning Our Data
# A. Write a profit_margin function that accepts a row of data, which is a dictionary
#    It should return the result of dividing the profit column by the sales column (i.e. profit/sales)
def profit_margin(row):
    profit = row['profit']
    sales = row['sales']
    return profit / sales

In [52]:
# B. Create a new column in the orders dataframe called 'profit_margin' by applying the profit margin function row-by-row
orders['profit_margin'] =orders.apply(profit_margin, axis=1)
orders.head(2)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id,profit_margin
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0,0.0
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0,0.0

In [17]:
# NO CODE HERE PLEASE

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id,profit_margin
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0,0.0
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0,0.0

We also want to create a column called `margin_categorization` that categorizes our new profit margin as "profitable", "unprofitable", or "break even". We can create a new function to do this, and then apply it to our orders DataFrame using the same method as above.

The function should follow these rules:
- If the profit_margin is greater than 0, the function should return "profitable"
- If the profit_margin is 0, the function should return "break even"
- If the profit_margin is less than 0, the function should return "unprofitable"

In [53]:
# C. Use the same process to create a new column called margin_category
# If the profit_margin is less than 0, the margin_category should be "unprofitable"
# If the profit_margin is 0, the margin_category should be "break even"
# If the profit_margin is above 0, the margin_category should "profitable"
def margin_categorization(row):
    if row['profit_margin'] > 0:
        return "profitable"
    elif row['profit_margin'] == 0:
        return "break even"
    else:
        return "unprofitable"

# apply the function to the orders dataframe 
# to create the new column 'margin_category'
orders['margin_category'] = orders.apply(margin_categorization, axis=1)
orders.head(2)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,postal_code,region_id,profit_margin,margin_category
0,CA-2016-2608109,17/09/2016 00:00,17/09/2016 00:00,Same Day,TT-21070,OFF-FA-10002280,45.0,9,0.00,0.0,90049.0,4553.0,0.0,break even
1,ES-2018-1945518,29/08/2018 00:00,02/09/2018 00:00,Same Day,AC-10420,OFF-FA-10001724,114.0,10,0.03,0.0,80013.0,4553.0,0.0,break even

Use the new `margin_category` column to find how many orders in the dataset were unprofitable. There are multiple ways to do this!

In [54]:
# D. How many of our orders were unprofitable?
# Hint: use .shape[0] to get number of rows of the dataframe
len(orders[orders['margin_category'] == 'unprofitable'])

11821

In [19]:
# NO CODE HERE PLEASE

11821